# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false


orbs:
  security-report: dreamquark-ai/security-report@1.0.1

executors:
  security-report: dreamquark-ai/security-report@1.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: make test-local

  docker-security:
    executor: security-report/default
    working_directory: /root/trademe
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.11
      - run:
          name: "Build & pull the images for security report"
          command: |
            echo $QUAY_PASSWORD | docker login -u $QUAY_LOGIN --password-stdin  quay.io
            docker pull quay.io/paulbarrie7/trademe:1.0.0
            make build IMAGE_NAME=quay.io/paulbarrie7/trademe IMAGE_TAG=security-test

      - security-report/security-report:
          image: 'quay.io/paulbarrie7/trademe'
          base-tag: '1.0.0'
          new-tag: 'security-test'
          orga: 'PaulBarrie'
          repo: 'trade-me'
          topic: 'trademe-security-report'

  sonar-test:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=PaulBarrie_trade-me

  deploy-docker:
    docker:
      - image: quay.io/paulbarrie7/docker:latest
    working_directory: /root/trademe
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.11
      - run:
          name: "Build the image"
          command: |
            make build IMAGE_NAME=quay.io/paulbarrie7/trademe IMAGE_TAG=latest
      - run:
          name: "Deploy the image"
          command: |
            echo $QUAY_PASSWORD | docker login -u $QUAY_LOGIN --password-stdin  quay.io
            make deploy IMAGE_NAME=quay.io/paulbarrie7/trademe IMAGE_TAG=latest

workflows:
  test:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - build-and-test:
          context:
            - ci-esgi
      - docker-security:
            context:
              - ci-esgi
      - sonar-test:
            context:
              - ci-esgi

  deploy:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - deploy-docker:
          context:
            - ci-esgi

